version: '3.8'

services:
  database:
    container_name: "cashier-db"
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_cashier
  prod:
    container_name: "cashier-service-prod"
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - '6969:3000'
    dns:
      - 8.8.8.8
    env_file:
      - ./.env
    network_mode: host

